name: Publish release candidate to GitHub Pages

on:
  push:
    branches:
      - 'release/**'

jobs:
  get-release-version:
    name: Get release version
    runs-on: ubuntu-20.04
    steps:
      - name: Extract release version from branch name
        run: |
          BRANCH_NAME='${{ github.ref_name }}'
          echo "::set-output name=RELEASE_VERSION::v${BRANCH_NAME#release/}"
  publish-to-gh-pages:
    name: Publish build to `${{ needs.get-release-version.outputs.RELEASE_VERSION }}` directory of `gh-pages` branch
    uses: ./.github/workflows/publish-gh-pages.yml
    needs: get-release-version
    with:
      destination_dir: ${{ needs.get-release-version.outputs.RELEASE_VERSION }}
